import { Question } from "../../types"

export const dsaQuestions: Question[] = [
    { id: 'dsa_1', title: 'Explain Time vs Space Complexity (Big O)', difficulty: 'Concept', link: 'https://www.geeksforgeeks.org/analysis-of-algorithms-time-complexity-and-space-complexity/' },
    { id: 'dsa_2', title: 'Reverse a Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/reverse-linked-list/' },
    { id: 'dsa_3', title: 'Valid Parentheses', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-parentheses/' },
    { id: 'dsa_4', title: 'Two Sum', difficulty: 'Easy', link: 'https://leetcode.com/problems/two-sum/' },
    { id: 'dsa_5', title: 'Maximum Subarray (Kadane’s Algorithm)', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximum-subarray/' },
    { id: 'dsa_6', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
    { id: 'dsa_7', title: 'Invert Binary Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/invert-binary-tree/' },
    { id: 'dsa_8', title: 'Lowest Common Ancestor of a BST', difficulty: 'Medium', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
    { id: 'dsa_9', title: 'Merge k Sorted Lists', difficulty: 'Hard', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
    { id: 'dsa_10', title: 'Trapping Rain Water', difficulty: 'Hard', link: 'https://leetcode.com/problems/trapping-rain-water/' },
    { id: 'dsa_11', title: 'Find Median from Data Stream', difficulty: 'Hard', link: 'https://leetcode.com/problems/find-median-from-data-stream/' },
    { id: 'dsa_12', title: 'Detect Cycle in a Graph', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/detect-cycle-in-a-directed-graph/' },

    { id: 'dsa_13', title: 'Climbing Stairs', difficulty: 'Easy', link: 'https://leetcode.com/problems/climbing-stairs/' },
    { id: 'dsa_14', title: 'Binary Search', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-search/' },
    { id: 'dsa_15', title: 'Rotate Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-array/' },
    { id: 'dsa_16', title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
    { id: 'dsa_17', title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/' },
    { id: 'dsa_18', title: 'Majority Element', difficulty: 'Easy', link: 'https://leetcode.com/problems/majority-element/' },
    { id: 'dsa_19', title: 'Search Insert Position', difficulty: 'Easy', link: 'https://leetcode.com/problems/search-insert-position/' },
    { id: 'dsa_20', title: 'Contains Duplicate', difficulty: 'Easy', link: 'https://leetcode.com/problems/contains-duplicate/' },
    { id: 'dsa_21', title: 'Merge Sorted Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-sorted-array/' },
    { id: 'dsa_22', title: 'Remove Element', difficulty: 'Easy', link: 'https://leetcode.com/problems/remove-element/' },
    { id: 'dsa_23', title: 'Plus One', difficulty: 'Easy', link: 'https://leetcode.com/problems/plus-one/' },
    { id: 'dsa_24', title: 'Add Two Numbers', difficulty: 'Medium', link: 'https://leetcode.com/problems/add-two-numbers/' },
    { id: 'dsa_25', title: 'Merge Two Sorted Lists', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
    { id: 'dsa_26', title: 'Linked List Cycle', difficulty: 'Easy', link: 'https://leetcode.com/problems/linked-list-cycle/' },
    { id: 'dsa_27', title: 'Palindrome Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/palindrome-linked-list/' },
    { id: 'dsa_28', title: 'LRU Cache', difficulty: 'Hard', link: 'https://leetcode.com/problems/lru-cache/' },
    { id: 'dsa_29', title: 'Kth Largest Element in an Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
    { id: 'dsa_30', title: 'Product of Array Except Self', difficulty: 'Medium', link: 'https://leetcode.com/problems/product-of-array-except-self/' },
    { id: 'dsa_31', title: 'Subarray Sum Equals K', difficulty: 'Medium', link: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
    { id: 'dsa_32', title: 'Reverse Integer', difficulty: 'Medium', link: 'https://leetcode.com/problems/reverse-integer/' },
    { id: 'dsa_33', title: 'String to Integer (atoi)', difficulty: 'Medium', link: 'https://leetcode.com/problems/string-to-integer-atoi/' },
    { id: 'dsa_34', title: 'Longest Palindromic Substring', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
    { id: 'dsa_35', title: 'Container With Most Water', difficulty: 'Medium', link: 'https://leetcode.com/problems/container-with-most-water/' },
    { id: 'dsa_36', title: '3Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/3sum/' },
    { id: 'dsa_37', title: 'Group Anagrams', difficulty: 'Medium', link: 'https://leetcode.com/problems/group-anagrams/' },
    { id: 'dsa_38', title: 'Longest Common Prefix', difficulty: 'Easy', link: 'https://leetcode.com/problems/longest-common-prefix/' },
    { id: 'dsa_39', title: 'Valid Anagram', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-anagram/' },
    { id: 'dsa_40', title: 'Count Primes', difficulty: 'Medium', link: 'https://leetcode.com/problems/count-primes/' },
    { id: 'dsa_41', title: 'Power of Two', difficulty: 'Easy', link: 'https://leetcode.com/problems/power-of-two/' },
    { id: 'dsa_42', title: 'Factorial Trailing Zeroes', difficulty: 'Medium', link: 'https://leetcode.com/problems/factorial-trailing-zeroes/' },
    { id: 'dsa_43', title: 'Rotate Image', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-image/' },
    { id: 'dsa_44', title: 'Spiral Matrix', difficulty: 'Medium', link: 'https://leetcode.com/problems/spiral-matrix/' },
    { id: 'dsa_45', title: 'Set Matrix Zeroes', difficulty: 'Medium', link: 'https://leetcode.com/problems/set-matrix-zeroes/' },
    { id: 'dsa_46', title: 'Word Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-search/' },
    { id: 'dsa_47', title: 'Jump Game', difficulty: 'Medium', link: 'https://leetcode.com/problems/jump-game/' },
    { id: 'dsa_48', title: 'Unique Paths', difficulty: 'Medium', link: 'https://leetcode.com/problems/unique-paths/' },
    { id: 'dsa_49', title: 'Minimum Path Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-path-sum/' },
    { id: 'dsa_50', title: 'Course Schedule', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule/' },

    // 51–100
    { id: 'dsa_51', title: 'Top K Frequent Elements', difficulty: 'Medium', link: 'https://leetcode.com/problems/top-k-frequent-elements/' },
    { id: 'dsa_52', title: 'Combination Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/combination-sum/' },
    { id: 'dsa_53', title: 'Permutations', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutations/' },
    { id: 'dsa_54', title: 'Sudoku Solver', difficulty: 'Hard', link: 'https://leetcode.com/problems/sudoku-solver/' },
    { id: 'dsa_55', title: 'N Queens', difficulty: 'Hard', link: 'https://leetcode.com/problems/n-queens/' },
    { id: 'dsa_56', title: 'Word Break', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-break/' },
    { id: 'dsa_57', title: 'Longest Increasing Subsequence', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
    { id: 'dsa_58', title: 'Edit Distance', difficulty: 'Hard', link: 'https://leetcode.com/problems/edit-distance/' },
    { id: 'dsa_59', title: 'House Robber', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber/' },
    { id: 'dsa_60', title: 'House Robber II', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber-ii/' },
    { id: 'dsa_61', title: 'Coin Change', difficulty: 'Medium', link: 'https://leetcode.com/problems/coin-change/' },
    { id: 'dsa_62', title: 'Partition Equal Subset Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
    { id: 'dsa_63', title: 'Decode Ways', difficulty: 'Medium', link: 'https://leetcode.com/problems/decode-ways/' },
    { id: 'dsa_64', title: 'Minimum Window Substring', difficulty: 'Hard', link: 'https://leetcode.com/problems/minimum-window-substring/' },
    { id: 'dsa_65', title: 'Search in Rotated Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
    { id: 'dsa_66', title: 'Median of Two Sorted Arrays', difficulty: 'Hard', link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
    { id: 'dsa_67', title: 'Zigzag Level Order Traversal', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/' },
    { id: 'dsa_68', title: 'Binary Tree Level Order Traversal', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
    { id: 'dsa_69', title: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard', link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
    { id: 'dsa_70', title: 'Validate Binary Search Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/validate-binary-search-tree/' },
    { id: 'dsa_71', title: 'Binary Tree Diameter', difficulty: 'Easy', link: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
    { id: 'dsa_72', title: 'Balanced Binary Tree Check', difficulty: 'Easy', link: 'https://leetcode.com/problems/balanced-binary-tree/' },
    { id: 'dsa_73', title: 'Symmetric Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/symmetric-tree/' },
    { id: 'dsa_74', title: 'Min Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-stack/' },
    { id: 'dsa_75', title: 'Find Peak Element', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-peak-element/' },
    { id: 'dsa_76', title: 'Gas Station', difficulty: 'Medium', link: 'https://leetcode.com/problems/gas-station/' },
    { id: 'dsa_77', title: 'Insert Delete GetRandom O(1)', difficulty: 'Medium', link: 'https://leetcode.com/problems/insert-delete-getrandom-o1/' },
    { id: 'dsa_78', title: 'Intersection of Two Linked Lists', difficulty: 'Easy', link: 'https://leetcode.com/problems/intersection-of-two-linked-lists/' },
    { id: 'dsa_79', title: 'Reverse Nodes in k-Group', difficulty: 'Hard', link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },
    { id: 'dsa_80', title: 'LRU Cache', difficulty: 'Hard', link: 'https://leetcode.com/problems/lru-cache/' },
    { id: 'dsa_81', title: 'Course Schedule II', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule-ii/' },
    { id: 'dsa_82', title: 'Graph Bipartite Check', difficulty: 'Medium', link: 'https://leetcode.com/problems/is-graph-bipartite/' },
    { id: 'dsa_83', title: 'Number of Islands', difficulty: 'Medium', link: 'https://leetcode.com/problems/number-of-islands/' },
    { id: 'dsa_84', title: 'Surrounded Regions', difficulty: 'Medium', link: 'https://leetcode.com/problems/surrounded-regions/' },
    { id: 'dsa_85', title: 'Pacific Atlantic Water Flow', difficulty: 'Medium', link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
    { id: 'dsa_86', title: 'Minimum Height Trees', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-height-trees/' },
    { id: 'dsa_87', title: 'Network Delay Time', difficulty: 'Medium', link: 'https://leetcode.com/problems/network-delay-time/' },
    { id: 'dsa_88', title: 'Alien Dictionary', difficulty: 'Hard', link: 'https://www.lintcode.com/problem/892/' },
    { id: 'dsa_89', title: 'Kruskal MST (Minimum Spanning Tree)', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm/' },
    { id: 'dsa_90', title: 'Prim’s MST', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/prims-algorithm-using-priority-queue/' },
    { id: 'dsa_91', title: 'Bellman Ford Algorithm', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/' },
    { id: 'dsa_92', title: 'Dijkstra’s Algorithm', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/' },
    { id: 'dsa_93', title: 'Flood Fill', difficulty: 'Easy', link: 'https://leetcode.com/problems/flood-fill/' },
    { id: 'dsa_94', title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
    { id: 'dsa_95', title: 'Add Binary', difficulty: 'Easy', link: 'https://leetcode.com/problems/add-binary/' },
    { id: 'dsa_96', title: 'Climbing Stairs with Minimum Cost', difficulty: 'Easy', link: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
    { id: 'dsa_97', title: 'Valid Palindrome', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-palindrome/' },
    { id: 'dsa_98', title: 'Reorder List', difficulty: 'Medium', link: 'https://leetcode.com/problems/reorder-list/' },
    { id: 'dsa_99', title: 'Gas Station Problem', difficulty: 'Medium', link: 'https://leetcode.com/problems/gas-station/' },
    { id: 'dsa_100', title: 'Maximum Profit in Job Scheduling', difficulty: 'Hard', link: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/' },
    { id: 'dsa_101', title: 'Split Linked List in Parts', difficulty: 'Medium', link: 'https://leetcode.com/problems/split-linked-list-in-parts/' },
    { id: 'dsa_102', title: 'Odd Even Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/odd-even-linked-list/' },
    { id: 'dsa_103', title: 'Flatten a Multilevel Doubly Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/' },
    { id: 'dsa_104', title: 'Copy List with Random Pointer', difficulty: 'Medium', link: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
    { id: 'dsa_105', title: 'Remove Nth Node From End of List', difficulty: 'Medium', link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
    { id: 'dsa_106', title: 'Sort List', difficulty: 'Medium', link: 'https://leetcode.com/problems/sort-list/' },
    { id: 'dsa_107', title: 'Rotate List', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-list/' },
    { id: 'dsa_108', title: 'Reorder Routes to Make All Paths Lead to City Zero', difficulty: 'Medium', link: 'https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/' },
    { id: 'dsa_109', title: 'Reverse Words in a String', difficulty: 'Medium', link: 'https://leetcode.com/problems/reverse-words-in-a-string/' },
    { id: 'dsa_110', title: 'Basic Calculator II', difficulty: 'Medium', link: 'https://leetcode.com/problems/basic-calculator-ii/' },
    { id: 'dsa_111', title: 'Evaluate Reverse Polish Notation', difficulty: 'Medium', link: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
    { id: 'dsa_112', title: 'Min Cost to Connect All Points', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-cost-to-connect-all-points/' },
    { id: 'dsa_113', title: 'Redundant Connection', difficulty: 'Medium', link: 'https://leetcode.com/problems/redundant-connection/' },
    { id: 'dsa_114', title: 'Account Merge', difficulty: 'Medium', link: 'https://leetcode.com/problems/accounts-merge/' },
    { id: 'dsa_115', title: 'Evaluate Division', difficulty: 'Medium', link: 'https://leetcode.com/problems/evaluate-division/' },
    { id: 'dsa_116', title: 'Rotting Oranges', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotting-oranges/' },
    { id: 'dsa_117', title: 'Walls and Gates', difficulty: 'Medium', link: 'https://leetcode.com/problems/walls-and-gates/' },
    { id: 'dsa_118', title: 'Snakes and Ladders', difficulty: 'Medium', link: 'https://leetcode.com/problems/snakes-and-ladders/' },
    { id: 'dsa_119', title: 'Path With Minimum Effort', difficulty: 'Medium', link: 'https://leetcode.com/problems/path-with-minimum-effort/' },
    { id: 'dsa_120', title: 'Bus Routes', difficulty: 'Hard', link: 'https://leetcode.com/problems/bus-routes/' },
    { id: 'dsa_121', title: 'Sliding Window Maximum', difficulty: 'Hard', link: 'https://leetcode.com/problems/sliding-window-maximum/' },
    { id: 'dsa_122', title: 'K Closest Points to Origin', difficulty: 'Medium', link: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
    { id: 'dsa_123', title: 'Largest Rectangle in Histogram', difficulty: 'Hard', link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
    { id: 'dsa_124', title: 'Maximal Rectangle', difficulty: 'Hard', link: 'https://leetcode.com/problems/maximal-rectangle/' },
    { id: 'dsa_125', title: 'Daily Temperatures', difficulty: 'Medium', link: 'https://leetcode.com/problems/daily-temperatures/' },
    { id: 'dsa_126', title: 'Asteroid Collision', difficulty: 'Medium', link: 'https://leetcode.com/problems/asteroid-collision/' },
    { id: 'dsa_127', title: 'Online Stock Span', difficulty: 'Medium', link: 'https://leetcode.com/problems/online-stock-span/' },
    { id: 'dsa_128', title: 'Next Greater Element I', difficulty: 'Easy', link: 'https://leetcode.com/problems/next-greater-element-i/' },
    { id: 'dsa_129', title: 'Next Greater Element II', difficulty: 'Medium', link: 'https://leetcode.com/problems/next-greater-element-ii/' },
    { id: 'dsa_130', title: 'Largest Perimeter Triangle', difficulty: 'Easy', link: 'https://leetcode.com/problems/largest-perimeter-triangle/' },
    { id: 'dsa_131', title: 'Reconstruct Itinerary', difficulty: 'Hard', link: 'https://leetcode.com/problems/reconstruct-itinerary/' },
    { id: 'dsa_132', title: 'Word Ladder', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-ladder/' },
    { id: 'dsa_133', title: 'Word Ladder II', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-ladder-ii/' },
    { id: 'dsa_134', title: 'Minimum Cost to Cut a Stick', difficulty: 'Hard', link: 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/' },
    { id: 'dsa_135', title: 'Burst Balloons', difficulty: 'Hard', link: 'https://leetcode.com/problems/burst-balloons/' },
    { id: 'dsa_136', title: 'Distinct Subsequences', difficulty: 'Hard', link: 'https://leetcode.com/problems/distinct-subsequences/' },
    { id: 'dsa_137', title: 'Interleaving String', difficulty: 'Medium', link: 'https://leetcode.com/problems/interleaving-string/' },
    { id: 'dsa_138', title: 'Wildcard Matching', difficulty: 'Hard', link: 'https://leetcode.com/problems/wildcard-matching/' },
    { id: 'dsa_139', title: 'Regular Expression Matching', difficulty: 'Hard', link: 'https://leetcode.com/problems/regular-expression-matching/' },
    { id: 'dsa_140', title: 'Palindrome Partitioning', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindrome-partitioning/' },
    { id: 'dsa_141', title: 'Palindrome Partitioning II', difficulty: 'Hard', link: 'https://leetcode.com/problems/palindrome-partitioning-ii/' },
    { id: 'dsa_142', title: 'Minimum Knight Moves', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-knight-moves/' },
    { id: 'dsa_143', title: 'Swim in Rising Water', difficulty: 'Hard', link: 'https://leetcode.com/problems/swim-in-rising-water/' },
    { id: 'dsa_144', title: 'Shortest Path Visiting All Nodes', difficulty: 'Hard', link: 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/' },
    { id: 'dsa_145', title: 'Concatenated Words', difficulty: 'Hard', link: 'https://leetcode.com/problems/concatenated-words/' },
    { id: 'dsa_146', title: 'Maximum XOR of Two Numbers', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/' },
    { id: 'dsa_147', title: 'Palindromic Substrings', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindromic-substrings/' },
    { id: 'dsa_148', title: 'Find Min in Rotated Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
    { id: 'dsa_149', title: 'Search a 2D Matrix', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-a-2d-matrix/' },
    { id: 'dsa_150', title: 'Peak Index in Mountain Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/' }
];