import { Question } from "../../types"

export const hrQuestions: Question[] = [
    { id: 'hr_1', title: 'Tell me about a time you failed', difficulty: 'Medium', link: 'https://www.themuse.com/advice/tell-me-about-a-time-you-failed-sample-answers' },
    { id: 'hr_2', title: 'Describe a conflict with a coworker', difficulty: 'Hard', link: 'https://www.indeed.com/career-advice/interviewing/conflict-resolution-interview-questions' },
    { id: 'hr_3', title: 'Why do you want to work here?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/why-do-you-want-to-work-here-interview-question-answer' },
    { id: 'hr_4', title: 'What are your greatest strengths/weaknesses?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/what-are-your-strengths-and-weaknesses' },

    { id: 'hr_5', title: 'Tell me about yourself', difficulty: 'Easy', link: 'https://www.themuse.com/advice/tell-me-about-yourself-interview-question-answer' },
    { id: 'hr_6', title: 'Walk me through your resume', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/walk-me-through-your-resume' },
    { id: 'hr_7', title: 'Why should we hire you?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/why-should-we-hire-you' },
    { id: 'hr_8', title: 'Tell me about a time you showed leadership', difficulty: 'Medium', link: 'https://www.theforage.com/blog/interview-questions/leadership-examples' },
    { id: 'hr_9', title: 'Describe a time you worked under pressure', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/working-well-under-pressure' },
    { id: 'hr_10', title: 'Tell me about a time you had to learn something quickly', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-had-to-learn-something-quickly/' },

    { id: 'hr_11', title: 'Describe a time you went above and beyond', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/describe-situation-when-you-went-above-and-beyond' },
    { id: 'hr_12', title: 'Tell me about a time you made a mistake', difficulty: 'Medium', link: 'https://www.themuse.com/advice/tell-me-about-a-time-you-made-a-mistake-sample-answers' },
    { id: 'hr_13', title: 'Describe a time you disagreed with your manager', difficulty: 'Hard', link: 'https://biginterview.com/disagreed-with-your-boss/' },
    { id: 'hr_14', title: 'Tell me about a time you had to deal with ambiguity', difficulty: 'Hard', link: 'https://www.indeed.com/career-advice/interviewing/ambiguity-interview-questions' },
    { id: 'hr_15', title: 'Tell me about a time you worked in a team', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/teamwork-interview-questions' },

    { id: 'hr_16', title: 'Describe a time you had to handle a difficult client', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/difficult-customer-interview-question' },
    { id: 'hr_17', title: 'Tell me about a time you handled multiple priorities', difficulty: 'Medium', link: 'https://biginterview.com/multiple-tasks-priorities/' },
    { id: 'hr_18', title: 'Describe a project you are proud of', difficulty: 'Easy', link: 'https://www.themuse.com/advice/talking-about-proudest-achievement-interview-question' },
    { id: 'hr_19', title: 'Tell me about a time you had to meet a tight deadline', difficulty: 'Medium', link: 'https://www.naukri.com/career-guidance/how-do-you-handle-working-under-pressure-interview-question' },
    { id: 'hr_20', title: 'Tell me about a time you improved a process', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-improved-a-process/' },

    { id: 'hr_21', title: 'How do you handle feedback or criticism?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/how-do-you-handle-criticism' },
    { id: 'hr_22', title: 'Describe your communication style', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/communication-style-interview-question' },
    { id: 'hr_23', title: 'How do you handle stress?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/how-do-you-handle-stress-interview-question-answer' },
    { id: 'hr_24', title: 'What motivates you?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/what-motivates-you' },
    { id: 'hr_25', title: 'Tell me about your biggest professional achievement', difficulty: 'Medium', link: 'https://www.themuse.com/advice/what-is-your-greatest-professional-achievement' },

    { id: 'hr_26', title: 'Describe your ideal work environment', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/ideal-work-environment' },
    { id: 'hr_27', title: 'What are your career goals for the next 3–5 years?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/where-do-you-see-yourself-in-5-years' },
    { id: 'hr_28', title: 'How do you prioritize your work?', difficulty: 'Medium', link: 'https://biginterview.com/how-do-you-prioritize-your-work/' },
    { id: 'hr_29', title: 'Describe a time you had to say no', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-say-no/' },
    { id: 'hr_30', title: 'Describe a time you showed initiative', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/show-initiative-at-work' },

    { id: 'hr_31', title: 'Tell me about a time you resolved a team conflict', difficulty: 'Hard', link: 'https://www.indeed.com/career-advice/interviewing/team-conflict-interview-question' },
    { id: 'hr_32', title: 'Describe a time you had to persuade someone', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-persuaded-someone/' },
    { id: 'hr_33', title: 'Tell me about a time you had to adapt to change', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/adapt-to-change-interview-question' },
    { id: 'hr_34', title: 'Describe a time you had to work with a difficult teammate', difficulty: 'Hard', link: 'https://ca.indeed.com/career-advice/interviewing/difficult-coworker-interview-question' },
    { id: 'hr_35', title: 'Tell me about a time you received critical feedback', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-received-constructive-criticism/' },

    { id: 'hr_36', title: 'Describe a time you made a decision with incomplete data', difficulty: 'Hard', link: 'https://biginterview.com/tell-me-about-a-time-you-had-to-make-a-decision-without-all-the-information/' },
    { id: 'hr_37', title: 'Tell me about a time you handled a misunderstanding', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-a-misunderstanding-with-a-colleague/' },
    { id: 'hr_38', title: 'Describe a time you had to handle a complaint', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/handling-customer-complaints-interview-question' },
    { id: 'hr_39', title: 'Tell me about a time you failed to meet a deadline', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-missed-a-deadline/' },
    { id: 'hr_40', title: 'Describe a time you had to quickly change priorities', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-your-priorities-changed-quickly/' },

    { id: 'hr_41', title: 'How do you handle working with minimal supervision?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/work-with-little-supervision' },
    { id: 'hr_42', title: 'Do you prefer working in a team or alone?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/teamwork-or-working-independently' },
    { id: 'hr_43', title: 'How do you handle repetitive or boring tasks?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/how-do-you-stay-motivated' },
    { id: 'hr_44', title: 'Describe your decision-making style', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/decision-making-interview-questions' },
    { id: 'hr_45', title: 'How do you manage work–life balance?', difficulty: 'Easy', link: 'https://www.thebalancemoney.com/work-life-balance-interview-questions-2059696' },

    { id: 'hr_46', title: 'Tell me about a time you had to mentor or coach someone', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-coached-someone/' },
    { id: 'hr_47', title: 'Describe a time you delegated tasks effectively', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-when-you-delegated-work-effectively/' },
    { id: 'hr_48', title: 'Tell me about a time you handled confidential information', difficulty: 'Medium', link: 'https://interviewquestions.guru/handling-confidential-information/' },
    { id: 'hr_49', title: 'Describe a time you had to enforce a policy', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-enforce-a-policy/' },
    { id: 'hr_50', title: 'Tell me about a time you had to give negative feedback', difficulty: 'Hard', link: 'https://biginterview.com/tell-me-about-a-time-you-had-to-give-someone-difficult-feedback/' },

    { id: 'hr_51', title: 'What do you know about our company?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/interview-question-what-do-you-know-about-our-company' },
    { id: 'hr_52', title: 'Why are you leaving your current job?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/why-are-you-leaving-your-current-job' },
    { id: 'hr_53', title: 'Why is there a gap in your resume?', difficulty: 'Medium', link: 'https://www.themuse.com/advice/how-to-explain-employment-gaps' },
    { id: 'hr_54', title: 'Why did you change careers/fields?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/changing-careers-interview-question' },
    { id: 'hr_55', title: 'What are your salary expectations?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/pay-salary/salary-expectations' },

    { id: 'hr_56', title: 'What do you look for in a manager?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/what-do-you-look-for-in-a-manager-interview-question' },
    { id: 'hr_57', title: 'What do you look for in a team?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/what-do-you-look-for-in-a-team' },
    { id: 'hr_58', title: 'How do you handle disagreements in a team setting?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/team-disagreement-interview-question' },
    { id: 'hr_59', title: 'Describe your leadership style', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/leadership-style-interview-question' },
    { id: 'hr_60', title: 'How do you handle situations where you are wrong?', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-were-wrong/' },

    { id: 'hr_61', title: 'Tell me about a time you solved a difficult problem', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/problem-solving-interview-questions' },
    { id: 'hr_62', title: 'Describe a time you used data to make a decision', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-used-data-to-make-a-decision/' },
    { id: 'hr_63', title: 'Tell me about a time you streamlined a process', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-improved-a-process/' },
    { id: 'hr_64', title: 'Describe a time you disagreed but still supported a decision', difficulty: 'Hard', link: 'https://biginterview.com/tell-me-about-a-time-you-disagreed-with-a-decision/' },
    { id: 'hr_65', title: 'Tell me about a time you handled an ethical dilemma', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-faced-an-ethical-dilemma/' },

    { id: 'hr_66', title: 'How do you handle failure or setbacks?', difficulty: 'Medium', link: 'https://www.themuse.com/advice/how-do-you-deal-with-failure-interview-question-answer' },
    { id: 'hr_67', title: 'Describe a time you had to start something from scratch', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-started-something-new/' },
    { id: 'hr_68', title: 'Tell me about a time you took a risk at work', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-took-a-risk-at-work/' },
    { id: 'hr_69', title: 'Describe a time you had to deal with unclear instructions', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-received-unclear-instructions/' },
    { id: 'hr_70', title: 'Tell me about a time you had to compromise', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-compromise/' },

    { id: 'hr_71', title: 'What does success mean to you?', difficulty: 'Concept', link: 'https://www.indeed.com/career-advice/interviewing/what-does-success-mean-to-you' },
    { id: 'hr_72', title: 'How do you stay organized?', difficulty: 'Easy', link: 'https://www.indeed.com/career-advice/interviewing/how-do-you-stay-organized' },
    { id: 'hr_73', title: 'How do you handle constant changes or shifting requirements?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/adaptability-interview-questions' },
    { id: 'hr_74', title: 'What type of work culture do you thrive in?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/culture-fit-interview-questions' },
    { id: 'hr_75', title: 'How do you handle working with people from diverse backgrounds?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/diversity-interview-questions' },

    { id: 'hr_76', title: 'Describe a time you improved a relationship with a coworker', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-improved-a-relationship-at-work/' },
    { id: 'hr_77', title: 'Tell me about a time you had to deliver on a long-term project', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/long-term-project-interview-question' },
    { id: 'hr_78', title: 'Describe a time you solved a problem creatively', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-were-creative/' },
    { id: 'hr_79', title: 'Tell me about a time you had to work with limited resources', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-limited-resources/' },
    { id: 'hr_80', title: 'Describe a time you handled a sudden emergency at work', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-dealt-with-an-emergency-at-work/' },

    { id: 'hr_81', title: 'What do you do if you strongly disagree with your manager?', difficulty: 'Hard', link: 'https://biginterview.com/disagreed-with-your-boss/' },
    { id: 'hr_82', title: 'How do you handle a drop in performance or motivation?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/career-development/how-to-stay-motivated-at-work' },
    { id: 'hr_83', title: 'Describe a time you had to give a presentation', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/presentation-skills-interview-questions' },
    { id: 'hr_84', title: 'Tell me about a time you had to change your communication style', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-change-your-communication-style/' },
    { id: 'hr_85', title: 'Describe a time you received recognition at work', difficulty: 'Easy', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-were-recognized-for-your-work/' },

    { id: 'hr_86', title: 'What do you do when you don’t know the answer?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/what-to-do-when-you-dont-know-how-to-answer-an-interview-question' },
    { id: 'hr_87', title: 'Tell me about a time you worked with cross-functional teams', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-worked-on-a-cross-functional-team/' },
    { id: 'hr_88', title: 'Describe a time you had to implement feedback', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-implemented-feedback/' },
    { id: 'hr_89', title: 'Tell me about a time you onboarded to a new role quickly', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-learn-a-lot-quickly/' },
    { id: 'hr_90', title: 'Describe a time when you had competing deadlines', difficulty: 'Medium', link: 'https://biginterview.com/tell-me-about-a-time-you-had-competing-priorities/' },

    { id: 'hr_91', title: 'What do you do if you realize you made a serious mistake?', difficulty: 'Medium', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-made-a-mistake/' },
    { id: 'hr_92', title: 'Describe a time when you had to handle confidential/sensitive data', difficulty: 'Medium', link: 'https://interviewquestions.guru/handling-confidential-information/' },
    { id: 'hr_93', title: 'Tell me about a time you had to manage expectations with stakeholders', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-managed-expectations/' },
    { id: 'hr_94', title: 'Describe a time you changed someone’s mind', difficulty: 'Hard', link: 'https://biginterview.com/change-someones-mind/' },
    { id: 'hr_95', title: 'Tell me about a time you had to deliver bad news', difficulty: 'Hard', link: 'https://interviewpenguin.com/tell-me-about-a-time-you-had-to-deliver-bad-news/' },

    { id: 'hr_96', title: 'What do you do in your first 90 days in this role?', difficulty: 'Concept', link: 'https://hbr.org/2012/05/the-first-90-days' },
    { id: 'hr_97', title: 'How do you evaluate your own performance?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/career-development/self-evaluation-examples' },
    { id: 'hr_98', title: 'What are you most proud of in your career so far?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/interview-question-what-are-you-most-proud-of' },
    { id: 'hr_99', title: 'Do you have any questions for us?', difficulty: 'Easy', link: 'https://www.themuse.com/advice/questions-to-ask-interviewer' },
    { id: 'hr_100', title: 'How would your manager and teammates describe you?', difficulty: 'Medium', link: 'https://www.indeed.com/career-advice/interviewing/how-would-your-boss-and-coworkers-describe-you' },
]