import { Question } from "../../types"

export const oodQuestions: Question[] = [
    { id: 'ood_1', title: 'Explain SOLID Principles', difficulty: 'Concept', link: 'https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/' },
    { id: 'ood_2', title: 'Inheritance vs Composition', difficulty: 'Medium', link: 'https://refactoring.guru/composition-over-inheritance' },
    { id: 'ood_3', title: 'Singleton Pattern: Implementation & Pros/Cons', difficulty: 'Easy', link: 'https://refactoring.guru/design-patterns/singleton' },
    { id: 'ood_4', title: 'Factory vs Abstract Factory Pattern', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/abstract-factory' },
    { id: 'ood_5', title: 'Design a Parking Lot System (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-parking-lot-using-object-oriented-principles/' },
    { id: 'ood_6', title: 'Polymorphism: Overloading vs Overriding', difficulty: 'Easy', link: 'https://www.geeksforgeeks.org/polymorphism-in-java/' },

    { id: 'ood_7', title: 'Strategy Pattern: When and How to Use', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/strategy' },
    { id: 'ood_8', title: 'Observer Pattern and Event Systems', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/observer' },
    { id: 'ood_9', title: 'Decorator Pattern for Extensible Behavior', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/decorator' },
    { id: 'ood_10', title: 'Adapter Pattern: Wrapping Legacy Code', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/adapter' },
    { id: 'ood_11', title: 'Facade Pattern: Simplifying Complex Systems', difficulty: 'Easy', link: 'https://refactoring.guru/design-patterns/facade' },
    { id: 'ood_12', title: 'Proxy Pattern: Virtual & Protection Proxy', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/proxy' },
    { id: 'ood_13', title: 'Builder Pattern for Complex Object Creation', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/builder' },
    { id: 'ood_14', title: 'Prototype Pattern and Object Cloning', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/prototype' },
    { id: 'ood_15', title: 'Command Pattern for Undo/Redo', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/command' },
    { id: 'ood_16', title: 'State Pattern vs Strategy Pattern', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/state' },
    { id: 'ood_17', title: 'Template Method Pattern', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/template-method' },
    { id: 'ood_18', title: 'Iterator Pattern and Collections', difficulty: 'Easy', link: 'https://refactoring.guru/design-patterns/iterator' },
    { id: 'ood_19', title: 'Composite Pattern for Tree Structures', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/composite' },
    { id: 'ood_20', title: 'Flyweight Pattern for Memory Optimization', difficulty: 'Hard', link: 'https://refactoring.guru/design-patterns/flyweight' },

    { id: 'ood_21', title: 'Mediator Pattern for Object Communication', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/mediator' },
    { id: 'ood_22', title: 'Memento Pattern for Saving State', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/memento' },
    { id: 'ood_23', title: 'Chain of Responsibility Pattern', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/chain-of-responsibility' },
    { id: 'ood_24', title: 'Visitor Pattern for Extensible Operations', difficulty: 'Hard', link: 'https://refactoring.guru/design-patterns/visitor' },
    { id: 'ood_25', title: 'Bridge Pattern: Decoupling Abstraction and Implementation', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/bridge' },
    { id: 'ood_26', title: 'Model-View-Controller (MVC) Pattern', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/mvc-design-pattern/' },
    { id: 'ood_27', title: 'MVVM Pattern in UI Applications', difficulty: 'Medium', link: 'https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/february/mvvm-wpf-apps-with-the-model-view-viewmodel-design-pattern' },
    { id: 'ood_28', title: 'Repository Pattern & Data Access Layer', difficulty: 'Medium', link: 'https://martinfowler.com/eaaCatalog/repository.html' },
    { id: 'ood_29', title: 'Dependency Injection and Inversion of Control', difficulty: 'Medium', link: 'https://martinfowler.com/articles/injection.html' },
    { id: 'ood_30', title: 'Domain-Driven Design: Entities and Value Objects', difficulty: 'Hard', link: 'https://martinfowler.com/bliki/EvansClassification.html' },

    { id: 'ood_31', title: 'UML Class Diagrams Basics', difficulty: 'Easy', link: 'https://www.uml-diagrams.org/class-diagrams-overview.html' },
    { id: 'ood_32', title: 'UML Sequence Diagrams Basics', difficulty: 'Easy', link: 'https://www.uml-diagrams.org/sequence-diagrams.html' },
    { id: 'ood_33', title: 'UML Use Case Diagrams Basics', difficulty: 'Easy', link: 'https://www.uml-diagrams.org/use-case-diagrams.html' },
    { id: 'ood_34', title: 'Cohesion vs Coupling in OOP Design', difficulty: 'Concept', link: 'https://www.geeksforgeeks.org/software-engineering-cohesion/' },
    { id: 'ood_35', title: 'GRASP Principles Overview', difficulty: 'Hard', link: 'https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)' },
    { id: 'ood_36', title: 'Clean Architecture (Onion / Hexagonal)', difficulty: 'Hard', link: 'https://8thlight.com/insights/hexagonal-architecture' },
    { id: 'ood_37', title: 'Common Anti-Patterns (God Object, Spaghetti Code, etc.)', difficulty: 'Medium', link: 'https://refactoring.guru/anti-patterns' },
    { id: 'ood_38', title: 'Object Pool Pattern', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/object-pool-design-pattern/' },
    { id: 'ood_39', title: 'Null Object Pattern', difficulty: 'Easy', link: 'https://refactoring.guru/design-patterns/null-object' },
    { id: 'ood_40', title: 'Specification Pattern', difficulty: 'Hard', link: 'https://martinfowler.com/apsupp/spec.pdf' },

    { id: 'ood_41', title: 'Design a Library Management System (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-library-management-system/' },
    { id: 'ood_42', title: 'Design an ATM System (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-an-atm/' },
    { id: 'ood_43', title: 'Design a Movie Ticket Booking System (BookMyShow)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-movie-ticket-booking-system-like-bookmyshow/' },
    { id: 'ood_44', title: 'Design an Elevator System (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-elevator-system/' },
    { id: 'ood_45', title: 'Design a Hotel Management System', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-hotel-management-system/' },
    { id: 'ood_46', title: 'Design a Restaurant Table Booking System', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-a-restaurant-management-system/' },
    { id: 'ood_47', title: 'Design an Online Shopping Cart System', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-shopping-cart-system/' },
    { id: 'ood_48', title: 'Design a Splitwise-like Expense Sharing System', difficulty: 'Hard', link: 'https://workat.tech/machine-coding/practice/splitwise-problem-article' },
    { id: 'ood_49', title: 'Design a Logging Framework', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/logging-system-design/' },
    { id: 'ood_50', title: 'Design a Rate Limiter', difficulty: 'Hard', link: 'https://leetcode.com/discuss/interview-question/system-design/124558/system-design-rate-limiter' },

    { id: 'ood_51', title: 'Design a Cache (LRU, LFU)', difficulty: 'Medium', link: 'https://leetcode.com/problems/lru-cache/' },
    { id: 'ood_52', title: 'Design a Notification Service (Email/SMS/Push)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-a-notification-system/' },
    { id: 'ood_53', title: 'Design a Chess Game (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-chess-game/' },
    { id: 'ood_54', title: 'Design a Tic-Tac-Toe Game', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-tic-tac-toe-game/' },
    { id: 'ood_55', title: 'Design a Snake & Ladder Game', difficulty: 'Medium', link: 'https://workat.tech/machine-coding/practice/snake-and-ladder-problem-article' },
    { id: 'ood_56', title: 'Design a Deck of Cards / Poker Game', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-a-deck-of-cards/' },
    { id: 'ood_57', title: 'Design a Social Media News Feed', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-news-feed-system/' },
    { id: 'ood_58', title: 'Design a URL Shortener (Core Classes)', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-a-url-shortener-like-tinyurl/' },
    { id: 'ood_59', title: 'Design a File Storage System (Google Drive-like)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-cloud-storage-system-like-google-drive/' },
    { id: 'ood_60', title: 'Design an Online Code Editor / IDE', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-online-code-editor/' },

    { id: 'ood_61', title: 'Thread-Safe Singleton Design', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/singleton#thread-safety' },
    { id: 'ood_62', title: 'Immutable Objects in OOP Design', difficulty: 'Medium', link: 'https://www.baeldung.com/java-immutable-object' },
    { id: 'ood_63', title: 'Value Objects vs Entities (DDD)', difficulty: 'Medium', link: 'https://martinfowler.com/bliki/ValueObject.html' },
    { id: 'ood_64', title: 'Aggregates and Aggregate Root', difficulty: 'Hard', link: 'https://martinfowler.com/bliki/DDD_Aggregate.html' },
    { id: 'ood_65', title: 'Repository and Unit of Work Patterns', difficulty: 'Hard', link: 'https://martinfowler.com/eaaCatalog/unitOfWork.html' },
    { id: 'ood_66', title: 'Event Sourcing Basics', difficulty: 'Hard', link: 'https://martinfowler.com/eaaDev/EventSourcing.html' },
    { id: 'ood_67', title: 'CQRS (Command Query Responsibility Segregation)', difficulty: 'Hard', link: 'https://martinfowler.com/bliki/CQRS.html' },
    { id: 'ood_68', title: 'Strategy vs State Pattern: Comparison', difficulty: 'Medium', link: 'https://stackoverflow.com/questions/1301776/whats-the-difference-between-the-state-and-strategy-patterns' },
    { id: 'ood_69', title: 'Composition Over Inheritance: Real Examples', difficulty: 'Medium', link: 'https://www.oracle.com/java/technologies/composition-versus-inheritance.html' },
    { id: 'ood_70', title: 'Refactoring to SOLID from a God Class', difficulty: 'Hard', link: 'https://refactoring.guru/refactoring/smells/large-class' },

    { id: 'ood_71', title: 'Design an Online Food Delivery System (LLD)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-food-delivery-system-like-uber-eats/' },
    { id: 'ood_72', title: 'Design a Ride Sharing System (Uber/Ola)', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-uber-system/' },
    { id: 'ood_73', title: 'Design a Chat / Messaging System', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-chat-application/' },
    { id: 'ood_74', title: 'Design a Leaderboard / Ranking System', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-leaderboard/' },
    { id: 'ood_75', title: 'Design a Notification Scheduler / Reminder System', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-a-task-scheduler/' },
    { id: 'ood_76', title: 'Design a Calendar / Meeting Scheduler', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-calendar-system/' },
    { id: 'ood_77', title: 'Design a Blogging Platform (Core OOD)', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-blogging-platform-like-medium/' },
    { id: 'ood_78', title: 'Design an Online Quiz / Exam System', difficulty: 'Medium', link: 'https://www.geeksforgeeks.org/design-online-test-system/' },
    { id: 'ood_79', title: 'Design a Payment Gateway Integration', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-payment-system/' },
    { id: 'ood_80', title: 'Design a Digital Wallet System', difficulty: 'Hard', link: 'https://www.geeksforgeeks.org/design-a-digital-wallet-system/' },

    { id: 'ood_81', title: 'Law of Demeter (Least Knowledge Principle)', difficulty: 'Concept', link: 'https://martinfowler.com/bliki/LawOfDemeter.html' },
    { id: 'ood_82', title: 'Tell, Don’t Ask Principle', difficulty: 'Concept', link: 'https://martinfowler.com/bliki/TellDontAsk.html' },
    { id: 'ood_83', title: 'DTO vs Entity vs ViewModel', difficulty: 'Medium', link: 'https://martinfowler.com/eaaCatalog/dataTransferObject.html' },
    { id: 'ood_84', title: 'Service Layer vs Repository Layer', difficulty: 'Medium', link: 'https://martinfowler.com/eaaCatalog/serviceLayer.html' },
    { id: 'ood_85', title: 'Hexagonal Architecture (Ports and Adapters)', difficulty: 'Hard', link: 'https://alistair.cockburn.us/hexagonal-architecture/' },
    { id: 'ood_86', title: 'SAGA Pattern for Distributed Transactions', difficulty: 'Hard', link: 'https://microservices.io/patterns/data/saga.html' },
    { id: 'ood_87', title: 'Factory Method vs Abstract Factory vs Builder', difficulty: 'Medium', link: 'https://refactoring.guru/design-patterns/factory-method' },
    { id: 'ood_88', title: 'Handling Enums and State Machines in OOP', difficulty: 'Medium', link: 'https://martinfowler.com/eaaDev/StateMachine.html' },
    { id: 'ood_89', title: 'Modeling Many-to-Many Relationships in OOP', difficulty: 'Medium', link: 'https://martinfowler.com/eaaCatalog/associationTableMapping.html' },
    { id: 'ood_90', title: 'Designing APIs for Extensibility and Backward Compatibility', difficulty: 'Hard', link: 'https://martinfowler.com/articles/enterpriseREST.html' },

    { id: 'ood_91', title: 'Design a Pluggable Analytics System', difficulty: 'Hard', link: 'https://martinfowler.com/articles/feature-toggles.html' },
    { id: 'ood_92', title: 'Design a Plugin Architecture (Modular Design)', difficulty: 'Hard', link: 'https://martinfowler.com/articles/microservices.html#ComponentizationViaServices' },
    { id: 'ood_93', title: 'Design a Feature Flag / Toggle System', difficulty: 'Medium', link: 'https://martinfowler.com/articles/feature-toggles.html' },
    { id: 'ood_94', title: 'Designing a Modular Monolith', difficulty: 'Hard', link: 'https://martinfowler.com/bliki/MonolithFirst.html' },
    { id: 'ood_95', title: 'Refactoring a God Class into Smaller Components', difficulty: 'Medium', link: 'https://refactoring.guru/smells/large-class' },
    { id: 'ood_96', title: 'Identifying and Removing Code Smells', difficulty: 'Medium', link: 'https://refactoring.guru/refactoring/smells' },
    { id: 'ood_97', title: 'Using Interfaces and Abstractions for Testability', difficulty: 'Medium', link: 'https://martinfowler.com/articles/mocksArentStubs.html' },
    { id: 'ood_98', title: 'Designing for Test-Driven Development (TDD)', difficulty: 'Medium', link: 'https://martinfowler.com/bliki/TestDrivenDevelopment.html' },
    { id: 'ood_99', title: 'Versioning Object Models and APIs Safely', difficulty: 'Hard', link: 'https://martinfowler.com/articles/consumerDrivenContracts.html' },
    { id: 'ood_100', title: 'Designing a Rule Engine (Configurable Business Rules)', difficulty: 'Hard', link: 'https://martinfowler.com/bliki/RulesEngine.html' },
];

// --- GROUPED VIEWS (like Fundamentals / Advanced / System & Architecture) ---

const OOD_FUNDAMENTALS_IDS = new Set<string>([
    'ood_1',
    'ood_2',
    'ood_3',
    'ood_4',
    'ood_6',
    'ood_7',
    'ood_8',
    'ood_9',
    'ood_10',
    'ood_11',
    'ood_12',
    'ood_13',
    'ood_14',
    'ood_15',
    'ood_16',
    'ood_17',
    'ood_18',
    'ood_19',
    'ood_20',
    'ood_21',
    'ood_22',
    'ood_23',
    'ood_25',
    'ood_31',
    'ood_32',
    'ood_33',
    'ood_34',
    'ood_37',
    'ood_38',
    'ood_39',
    'ood_61',
    'ood_62',
    'ood_68',
    'ood_69',
    'ood_81',
    'ood_82',
    'ood_83',
    'ood_84',
    'ood_87',
    'ood_88',
    'ood_89',
    'ood_95',
    'ood_96',
    'ood_97',
    'ood_98',
]);

const OOD_ADVANCED_IDS = new Set<string>([
    'ood_24',
    'ood_30',
    'ood_35',
    'ood_36',
    'ood_40',
    'ood_63',
    'ood_64',
    'ood_65',
    'ood_66',
    'ood_67',
    'ood_70',
    'ood_85',
    'ood_86',
    'ood_90',
    'ood_99',
    'ood_100',
]);

export const oodFundamentals: Question[] = oodQuestions.filter(q =>
    OOD_FUNDAMENTALS_IDS.has(q.id)
);

export const oodAdvanced: Question[] = oodQuestions.filter(q =>
    OOD_ADVANCED_IDS.has(q.id)
);

// Everything else (LLD problems + high-level architecture/system-style topics)
export const oodSystemAndArchitecture: Question[] = oodQuestions.filter(
    q => !OOD_FUNDAMENTALS_IDS.has(q.id) && !OOD_ADVANCED_IDS.has(q.id)
);